[package]
name = "noctune"
version = "0.1.0"
edition = "2021"
authors = ["wendellocf <wendellocf@gmail.com>"]
description = "A fully customizable terminal music player with ASCII art TUI"
license = "MIT"
repository = "https://github.com/wendellocf/noctune"

[dependencies]
# TUI
ratatui = "0.29"
crossterm = "0.28"

# Audio
rodio = { version = "0.20", default-features = false, features = ["symphonia-all"] }
cpal = "0.15"
symphonia = { version = "0.5", features = ["all"] }

# Config & themes
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"

# Utils
anyhow = "1"
thiserror = "2"
directories = "5"
walkdir = "2"
notify = "6"
unicode-width = "0.2"
rustfft = "6"
parking_lot = "0.12"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "blocking", "json"] }
url = "2"
sha2 = "0.10"
base64 = "0.22"
rand = "0.8"
tiny_http = "0.12"
webbrowser = "1"
discord-rich-presence = "1"

[profile.release]
lto = true
codegen-units = 1
strip = true
