//! Help reads the exact same command registry and live key bindings as the palette.
use crate::{i18n::Language, keybinds::Bindings, theme::Theme};
use ratatui::{
    layout::Rect,
    text::{Line, Span},
    widgets::{Block, Borders, Clear, Paragraph, Wrap},
    Frame,
};
use unicode_width::{UnicodeWidthChar, UnicodeWidthStr};

/// Trim a label to a terminal-cell width without splitting wide characters.
fn truncate_cells(text: &str, width: usize) -> String {
    if text.width() <= width {
        return text.to_owned();
    }
    if width == 0 {
        return String::new();
    }
    if width == 1 {
        return "…".to_owned();
    }

    let mut used = 1; // ellipsis
    let mut result = String::new();
    for ch in text.chars() {
        let cells = ch.width().unwrap_or(0);
        if used + cells > width {
            break;
        }
        result.push(ch);
        used += cells;
    }
    result.push('…');
    result
}

fn help_lines(bindings: &Bindings, language: Language, width: u16, theme: &Theme) -> Vec<Line<'static>> {
    let shortcuts: Vec<String> = crate::commands::COMMANDS
        .iter()
        .map(|command| bindings.shortcut(command.action))
        .collect();
    let widest_shortcut = shortcuts.iter().map(|shortcut| shortcut.width()).max().unwrap_or(0);
    // Keep the action readable even when a user has configured a very long chord.
    let shortcut_width = widest_shortcut.min((width as usize).saturating_sub(3) / 2);
    let action_width = (width as usize).saturating_sub(shortcut_width + 3);

    crate::commands::COMMANDS
        .iter()
        .zip(shortcuts)
        .map(|(command, shortcut)| {
            let shortcut = truncate_cells(&shortcut, shortcut_width);
            let padding = " ".repeat(shortcut_width.saturating_sub(shortcut.width()));
            let action = truncate_cells(command.title(language), action_width);
            Line::from(vec![
                Span::styled(format!(" {shortcut}{padding} "), theme.accent()),
                Span::raw("│ "),
                Span::raw(action),
            ])
        })
        .collect()
}

pub fn render_help(
    f: &mut Frame,
    area: Rect,
    scroll: u16,
    theme: &Theme,
    bindings: &Bindings,
    language: Language,
) {
    let popup = super::util::bounded_popup(area, 92, 30);
    f.render_widget(Clear, popup);
    let block = Block::default()
        .borders(Borders::ALL)
        .border_style(theme.border(true))
        .title(language.text(
            " Help — commands and current shortcuts ",
            " Ajuda — comandos e atalhos atuais ",
        ))
        .title_bottom(language.text(
            " Up/Down: scroll | Esc: close ",
            " Cima/Baixo: rolar | Esc: fechar ",
        ));
    let inner = block.inner(popup);
    f.render_widget(block, popup);
    let lines = help_lines(bindings, language, inner.width, theme);
    f.render_widget(
        Paragraph::new(lines)
            .scroll((scroll, 0))
            .wrap(Wrap { trim: false }),
        inner,
    );
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn help_fits_small_terminals_and_shows_overrides() {
        let config = crate::config::Keybinds {
            play_pause: "Ctrl+x".into(),
            ..crate::config::Config::default().keybinds
        };
        let (bindings, _) = Bindings::from_config(&config);
        let theme: Theme = toml::from_str(include_str!("../../themes/default.toml")).unwrap();
        for (width, height) in [(20, 8), (80, 24), (120, 30)] {
            let mut terminal =
                ratatui::Terminal::new(ratatui::backend::TestBackend::new(width, height)).unwrap();
            for (language, title) in [
                (Language::En, "Help"),
                (Language::PtBr, "Ajuda"),
                (Language::En, "Help"),
            ] {
                terminal
                    .draw(|f| render_help(f, f.area(), 0, &theme, &bindings, language))
                    .unwrap();
                assert_eq!(terminal.backend().buffer().area.width, width);
                let rendered: String = terminal
                    .backend()
                    .buffer()
                    .content
                    .iter()
                    .map(|cell| cell.symbol())
                    .collect();
                assert!(rendered.contains(title));
                assert!(!rendered.contains(if language == Language::En {
                    "Ajuda"
                } else {
                    "Help"
                }));
            }
        }
        assert!(crate::commands::markdown(&bindings, Language::En).contains("Ctrl+x"));
        let portuguese = crate::commands::markdown(&bindings, Language::PtBr);
        assert!(portuguese.contains("# Atalhos do Noctune"));
        assert!(portuguese.contains("Ctrl+x"));
        assert!(!portuguese.contains("Generated by"));
    }

    #[test]
    fn help_uses_compact_aligned_shortcut_rows() {
        let (bindings, _) = Bindings::from_config(&crate::config::Config::default().keybinds);
        let theme: Theme = toml::from_str(include_str!("../../themes/default.toml")).unwrap();
        let lines = help_lines(&bindings, Language::PtBr, 80, &theme);

        assert_eq!(lines.len(), crate::commands::COMMANDS.len());
        assert!(lines[0].to_string().contains("Alternar português / inglês"));
        assert!(lines.iter().all(|line| line.to_string().contains('│')));
    }
}
